// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseAnon() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Term\xE9kek keres\xE9se",
  description: "Keres\xE9s a webshop nyilv\xE1nos term\xE9kkatal\xF3gus\xE1ban n\xE9v, m\xE1rka vagy le\xEDr\xE1s alapj\xE1n.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keres\u0151kifejez\xE9s."),
    limit: z.number().int().min(1).max(50).default(10).describe("Tal\xE1latok maximuma.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("shop_products").select("id,name,slug,brand,price,currency,stock_quantity,description,image_url").or(`name.ilike.%${query}%,brand.ilike.%${query}%,description.ilike.%${query}%`).eq("is_active", true).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseAnon2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Term\xE9k r\xE9szletei",
  description: "Egyetlen webshop term\xE9k r\xE9szletes adatai slug vagy id alapj\xE1n.",
  inputSchema: {
    idOrSlug: z2.string().trim().min(1).describe("Term\xE9k id (uuid) vagy slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ idOrSlug }) => {
    const supabase = supabaseAnon2();
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(idOrSlug);
    const { data, error } = await supabase.from("shop_products").select("*").eq(isUuid ? "id" : "slug", idOrSlug).eq("is_active", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Nincs ilyen term\xE9k." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "Saj\xE1t rendel\xE9sek list\xE1ja",
  description: "A bejelentkezett felhaszn\xE1l\xF3 rendel\xE9seinek list\xE1ja (legut\xF3bbiak el\xF6l).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nem vagy bejelentkezve." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select("id,order_number,status,total_amount,currency,created_at,tracking_number").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-order.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_order_default = defineTool4({
  name: "get_my_order",
  title: "Saj\xE1t rendel\xE9s r\xE9szletei",
  description: "Egy adott saj\xE1t rendel\xE9s r\xE9szletes adatai + sz\xE1ll\xEDt\xE1si esem\xE9nyek.",
  inputSchema: {
    orderId: z4.string().trim().min(1).describe("A rendel\xE9s id-je vagy rendel\xE9ssz\xE1ma.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ orderId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nem vagy bejelentkezve." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(orderId);
    const { data: order, error } = await supabase.from("orders").select("*").eq(isUuid ? "id" : "order_number", orderId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!order) {
      return { content: [{ type: "text", text: "Nincs ilyen rendel\xE9sed." }], isError: true };
    }
    const { data: events } = await supabase.from("order_events").select("event_type,created_at,details").eq("order_id", order.id).order("created_at", { ascending: true });
    const result = { order, events: events ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
var whoami_default = defineTool5({
  name: "whoami",
  title: "Ki vagyok bejelentkezve",
  description: "Visszaadja a h\xEDv\xF3 f\xE9l felhaszn\xE1l\xF3i azonos\xEDt\xF3j\xE1t \xE9s email c\xEDm\xE9t.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nem vagy bejelentkezve." }], isError: true };
    }
    const info = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "meyxhsgnryuupwpddxav";
var mcp_default = defineMcp({
  name: "egyszerudenagyszeru-mcp",
  title: "Egyszer\u0171 de Nagyszer\u0171 MCP",
  version: "0.1.0",
  instructions: "Tool-ok az Egyszer\u0171 de Nagyszer\u0171 webshophoz. Keress term\xE9keket a katal\xF3gusban (search_products, get_product), vagy a bejelentkezett felhaszn\xE1l\xF3 nev\xE9ben k\xE9rdezd le a saj\xE1t rendel\xE9seit (list_my_orders, get_my_order). A whoami visszaadja a bejelentkezett felhaszn\xE1l\xF3 azonos\xEDt\xF3j\xE1t.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_orders_default, get_my_order_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
