ALTER TABLE public.store_settings
  ADD COLUMN IF NOT EXISTS payment_transfer_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS payment_transfer_bank_name text,
  ADD COLUMN IF NOT EXISTS payment_transfer_iban text,
  ADD COLUMN IF NOT EXISTS payment_installment_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS payment_installment_months integer DEFAULT 3,
  ADD COLUMN IF NOT EXISTS payment_min_order_amount numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shipping_zones jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS stock_alert_email text,
  ADD COLUMN IF NOT EXISTS stock_auto_reorder_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS stock_auto_reorder_threshold integer DEFAULT 5,
  ADD COLUMN IF NOT EXISTS stock_show_remaining_count boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS stock_show_availability_text boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS appearance_product_card_style text DEFAULT 'default',
  ADD COLUMN IF NOT EXISTS appearance_header_style text DEFAULT 'default',
  ADD COLUMN IF NOT EXISTS appearance_footer_style text DEFAULT 'default',
  ADD COLUMN IF NOT EXISTS appearance_announcement_bar_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS appearance_announcement_bar_text text,
  ADD COLUMN IF NOT EXISTS appearance_announcement_bar_bg_color text DEFAULT '#000000';