
ALTER TABLE public.partner_storefronts
  ADD COLUMN IF NOT EXISTS topbar_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS topbar_text text DEFAULT 'Üdv a boltban! Nézd meg a kollekciókat.',
  ADD COLUMN IF NOT EXISTS topbar_icon text DEFAULT 'flame',
  ADD COLUMN IF NOT EXISTS hero_layout text NOT NULL DEFAULT 'split',
  ADD COLUMN IF NOT EXISTS hero_badge_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hero_badge_text text DEFAULT 'Új kollekció',
  ADD COLUMN IF NOT EXISTS hero_overlay_opacity numeric NOT NULL DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS section1_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS section1_title text,
  ADD COLUMN IF NOT EXISTS section1_subtitle text,
  ADD COLUMN IF NOT EXISTS section1_image_url text,
  ADD COLUMN IF NOT EXISTS section1_cta_text text,
  ADD COLUMN IF NOT EXISTS section1_cta_url text,
  ADD COLUMN IF NOT EXISTS section2_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS section2_title text,
  ADD COLUMN IF NOT EXISTS section2_subtitle text,
  ADD COLUMN IF NOT EXISTS section2_image_url text,
  ADD COLUMN IF NOT EXISTS section2_cta_text text,
  ADD COLUMN IF NOT EXISTS section2_cta_url text,
  ADD COLUMN IF NOT EXISTS featured_products_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS featured_products_title text DEFAULT 'Kiemelt termékek',
  ADD COLUMN IF NOT EXISTS featured_product_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS testimonials_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS testimonials_title text DEFAULT 'Vásárlóink mondták',
  ADD COLUMN IF NOT EXISTS testimonials jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS newsletter_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS newsletter_title text DEFAULT 'Iratkozz fel hírlevelünkre',
  ADD COLUMN IF NOT EXISTS newsletter_subtitle text DEFAULT 'Kapj értesítést új termékekről és akciókról.',
  ADD COLUMN IF NOT EXISTS footer_text text,
  ADD COLUMN IF NOT EXISTS footer_links jsonb NOT NULL DEFAULT '[]'::jsonb;
