
CREATE TABLE public.store_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_name TEXT NOT NULL DEFAULT 'Egyszerű de Nagyszerű',
  logo_url TEXT,
  currency TEXT NOT NULL DEFAULT 'HUF',
  shipping_fee NUMERIC NOT NULL DEFAULT 1490,
  free_shipping_above NUMERIC DEFAULT 15000,
  contact_email TEXT,
  contact_phone TEXT,
  contact_address TEXT,
  -- Payment
  payment_cash_enabled BOOLEAN DEFAULT false,
  payment_card_enabled BOOLEAN DEFAULT true,
  payment_cod_enabled BOOLEAN DEFAULT false,
  -- Email notifications
  email_order_confirmation BOOLEAN DEFAULT true,
  email_shipping_notification BOOLEAN DEFAULT true,
  email_coupon_notification BOOLEAN DEFAULT false,
  -- Social
  social_facebook TEXT,
  social_instagram TEXT,
  social_tiktok TEXT,
  social_youtube TEXT,
  social_twitter TEXT,
  social_pinterest TEXT,
  reply_to_email TEXT,
  sender_name TEXT,
  -- SEO
  seo_title TEXT,
  seo_description TEXT,
  seo_keywords TEXT,
  seo_og_image_url TEXT,
  seo_canonical_url TEXT,
  seo_robots TEXT DEFAULT 'index, follow',
  seo_google_analytics_id TEXT,
  seo_search_console_code TEXT,
  seo_structured_data_enabled BOOLEAN DEFAULT false,
  -- Theme
  theme_primary_color TEXT,
  theme_accent_color TEXT,
  theme_font_heading TEXT,
  theme_font_body TEXT,
  theme_bg_color TEXT,
  theme_button_radius TEXT,
  theme_logo_position TEXT DEFAULT 'left',
  theme_favicon_url TEXT,
  theme_header_height TEXT,
  theme_footer_text TEXT,
  theme_custom_css TEXT,
  -- Business hours
  business_hours JSONB,
  auto_reply_message TEXT,
  -- Legal
  terms_and_conditions TEXT,
  privacy_policy TEXT,
  custom_order_statuses JSONB,
  size_chart_template TEXT,
  return_policy TEXT,
  warranty_info TEXT,
  -- Loyalty
  loyalty_enabled BOOLEAN DEFAULT false,
  loyalty_points_per_currency NUMERIC DEFAULT 1,
  loyalty_discount_per_points NUMERIC DEFAULT 100,
  loyalty_min_redeem INTEGER DEFAULT 100,
  loyalty_redemption_rate NUMERIC DEFAULT 1,
  loyalty_levels TEXT[] DEFAULT '{"Bronz","Ezüst","Arany","Platina"}',
  loyalty_expiry_months INTEGER DEFAULT 12,
  -- Reviews
  reviews_enabled BOOLEAN DEFAULT true,
  reviews_require_approval BOOLEAN DEFAULT true,
  -- Shipping
  shipping_methods JSONB,
  -- Inventory
  low_stock_threshold INTEGER DEFAULT 5,
  auto_hide_out_of_stock BOOLEAN DEFAULT false,
  -- Notifications
  notification_new_order BOOLEAN DEFAULT true,
  notification_low_stock BOOLEAN DEFAULT true,
  notification_new_review BOOLEAN DEFAULT true,
  notification_email TEXT,
  -- Invoicing
  invoice_company_name TEXT,
  invoice_tax_number TEXT,
  invoice_bank_account TEXT,
  invoice_address TEXT,
  invoice_header_text TEXT,
  invoice_footer_text TEXT,
  -- Checkout
  checkout_require_phone BOOLEAN DEFAULT true,
  checkout_require_city BOOLEAN DEFAULT true,
  checkout_require_zip BOOLEAN DEFAULT true,
  checkout_enable_notes BOOLEAN DEFAULT true,
  checkout_enable_gift_wrap BOOLEAN DEFAULT false,
  checkout_gift_wrap_price NUMERIC DEFAULT 500,
  checkout_min_order_amount NUMERIC DEFAULT 0,
  checkout_success_message TEXT,
  -- Cookie
  cookie_banner_enabled BOOLEAN DEFAULT true,
  cookie_banner_text TEXT DEFAULT 'Ez az oldal sütiket használ a jobb élmény érdekében.',
  cookie_banner_button_text TEXT DEFAULT 'Elfogadom',
  cookie_banner_position TEXT DEFAULT 'bottom',
  -- Maintenance
  maintenance_enabled BOOLEAN DEFAULT false,
  maintenance_message TEXT,
  maintenance_password TEXT,
  -- Popups
  popup_newsletter_enabled BOOLEAN DEFAULT false,
  popup_newsletter_title TEXT,
  popup_newsletter_text TEXT,
  popup_newsletter_delay_seconds INTEGER DEFAULT 5,
  popup_exit_enabled BOOLEAN DEFAULT false,
  popup_exit_title TEXT,
  popup_exit_text TEXT,
  popup_promo_enabled BOOLEAN DEFAULT false,
  popup_promo_title TEXT,
  popup_promo_text TEXT,
  popup_promo_image_url TEXT,
  -- Email templates
  email_welcome_enabled BOOLEAN DEFAULT true,
  email_welcome_subject TEXT,
  email_welcome_body TEXT,
  email_abandoned_cart_enabled BOOLEAN DEFAULT false,
  email_abandoned_cart_delay_hours INTEGER DEFAULT 24,
  email_review_request_enabled BOOLEAN DEFAULT false,
  email_review_request_delay_days INTEGER DEFAULT 7,
  -- Language
  lang_default TEXT DEFAULT 'hu',
  lang_available TEXT[] DEFAULT '{"hu"}',
  lang_auto_detect BOOLEAN DEFAULT false,
  -- Discount rules
  discount_quantity_enabled BOOLEAN DEFAULT false,
  discount_quantity_rules JSONB,
  discount_vip_enabled BOOLEAN DEFAULT false,
  discount_vip_tiers JSONB,
  discount_auto_enabled BOOLEAN DEFAULT false,
  discount_auto_min_amount NUMERIC DEFAULT 0,
  discount_auto_value NUMERIC DEFAULT 0,
  discount_auto_type TEXT DEFAULT 'percentage',
  -- Product display
  product_default_view TEXT DEFAULT 'grid',
  product_grid_columns INTEGER DEFAULT 3,
  product_items_per_page INTEGER DEFAULT 12,
  product_default_sort TEXT DEFAULT 'newest',
  product_quick_view_enabled BOOLEAN DEFAULT true,
  product_show_stock_badge BOOLEAN DEFAULT true,
  product_show_discount_badge BOOLEAN DEFAULT true,
  -- Registration
  reg_require_name BOOLEAN DEFAULT true,
  reg_require_phone BOOLEAN DEFAULT false,
  reg_require_address BOOLEAN DEFAULT false,
  reg_social_login_enabled BOOLEAN DEFAULT false,
  reg_terms_required BOOLEAN DEFAULT true,
  reg_welcome_message TEXT,
  -- Analytics
  analytics_enabled BOOLEAN DEFAULT false,
  analytics_meta_pixel_id TEXT,
  analytics_gtm_id TEXT,
  analytics_tiktok_pixel_id TEXT,
  analytics_fb_conversions_token TEXT,
  analytics_custom_head_code TEXT,
  analytics_custom_body_code TEXT,
  -- Cookie extended
  cookie_analytics_enabled BOOLEAN DEFAULT false,
  cookie_marketing_enabled BOOLEAN DEFAULT false,
  cookie_functional_enabled BOOLEAN DEFAULT true,
  cookie_privacy_url TEXT,
  cookie_expiry_days INTEGER DEFAULT 365,
  -- Notification extended
  notification_slack_webhook TEXT,
  notification_new_user BOOLEAN DEFAULT false,
  notification_cancelled_order BOOLEAN DEFAULT true,
  notification_daily_summary BOOLEAN DEFAULT false,
  -- Maintenance extended
  maintenance_return_date TEXT,
  maintenance_ip_whitelist TEXT,
  maintenance_banner_text TEXT,
  -- Payment extended
  payment_transfer_enabled BOOLEAN DEFAULT false,
  payment_transfer_bank_name TEXT,
  payment_transfer_iban TEXT,
  payment_installment_enabled BOOLEAN DEFAULT false,
  payment_installment_months INTEGER DEFAULT 3,
  payment_min_order_amount NUMERIC DEFAULT 0,
  -- Shipping zones
  shipping_zones JSONB,
  shipping_free_limit NUMERIC DEFAULT 15000,
  shipping_default_cost NUMERIC DEFAULT 1490,
  -- Stock alerts
  stock_alert_enabled BOOLEAN DEFAULT true,
  stock_alert_email TEXT,
  stock_alert_threshold INTEGER DEFAULT 5,
  stock_auto_hide BOOLEAN DEFAULT false,
  stock_auto_reorder_enabled BOOLEAN DEFAULT false,
  stock_auto_reorder_threshold INTEGER DEFAULT 3,
  stock_show_remaining_count BOOLEAN DEFAULT true,
  stock_show_availability_text BOOLEAN DEFAULT true,
  -- SEO extended
  seo_meta_title TEXT,
  seo_meta_description TEXT,
  seo_og_image TEXT,
  seo_sitemap_enabled BOOLEAN DEFAULT true,
  -- Appearance extended
  appearance_product_card_style TEXT DEFAULT 'default',
  appearance_header_style TEXT DEFAULT 'default',
  appearance_footer_style TEXT DEFAULT 'default',
  appearance_announcement_bar_enabled BOOLEAN DEFAULT false,
  appearance_announcement_bar_text TEXT,
  appearance_announcement_bar_bg_color TEXT,
  -- Coupon settings
  coupon_auto_apply_enabled BOOLEAN DEFAULT false,
  coupon_stackable BOOLEAN DEFAULT false,
  coupon_max_per_user INTEGER DEFAULT 1,
  coupon_first_order_discount BOOLEAN DEFAULT false,
  coupon_first_order_value NUMERIC DEFAULT 0,
  -- Product tags
  product_tags JSONB DEFAULT '[]',
  product_filter_by_color BOOLEAN DEFAULT true,
  product_filter_by_size BOOLEAN DEFAULT true,
  product_filter_by_price BOOLEAN DEFAULT true,
  product_filter_by_material BOOLEAN DEFAULT false,
  -- User notifications
  notif_push_enabled BOOLEAN DEFAULT false,
  notif_sms_enabled BOOLEAN DEFAULT false,
  notif_sms_provider TEXT,
  notif_order_status_sms BOOLEAN DEFAULT false,
  notif_promo_push BOOLEAN DEFAULT false,
  -- Order workflow
  order_auto_confirm BOOLEAN DEFAULT false,
  order_auto_cancel_hours INTEGER DEFAULT 48,
  order_require_payment_proof BOOLEAN DEFAULT false,
  order_workflow_steps JSONB DEFAULT '[]',
  -- Product comparison
  compare_enabled BOOLEAN DEFAULT true,
  compare_max_products INTEGER DEFAULT 4,
  compare_show_differences_only BOOLEAN DEFAULT false,
  -- Return rules
  return_auto_approve BOOLEAN DEFAULT false,
  return_deadline_days INTEGER DEFAULT 14,
  return_reasons TEXT[] DEFAULT '{"Nem tetszik","Hibás termék","Rossz méret","Egyéb"}',
  return_refund_method TEXT DEFAULT 'original',
  -- Gift cards
  giftcard_enabled BOOLEAN DEFAULT false,
  giftcard_min_amount NUMERIC DEFAULT 1000,
  giftcard_max_amount NUMERIC DEFAULT 50000,
  giftcard_expiry_months INTEGER DEFAULT 12,
  giftcard_custom_design BOOLEAN DEFAULT false,
  -- i18n
  i18n_auto_translate BOOLEAN DEFAULT false,
  i18n_default_language TEXT DEFAULT 'hu',
  i18n_supported_languages TEXT[] DEFAULT '{"hu"}',
  i18n_show_switcher BOOLEAN DEFAULT false
);

ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read settings" ON public.store_settings FOR SELECT USING (true);
CREATE POLICY "Admins can update settings" ON public.store_settings FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin'));

-- Insert default row
INSERT INTO public.store_settings (store_name) VALUES ('Egyszerű de Nagyszerű');
