// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnjoaoofknmvttqmprxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuam9hb29ma25tdnR0cW1wcnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MDk3NTYsImV4cCI6MjA1OTQ4NTc1Nn0.RgR-KKBRMZWBIeHVo21VWGpCuuUHGTzSsQAcfObhFtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});